openapi: 3.0.0
x-stoplight:
  id: 984571274919c
info:
  title: Store Logs V3 API
  version: ''
  description: Get store logs
servers:
  - url: 'https://api.bigcommerce.com'
paths:
  '/stores/{store_hash}/v3/store/systemlogs':
    get:
      summary: Get System Logs
      description: |- 
        Get system logs 

        <!-- theme:info -->
        > #### Note
        > The documented values for the `module` query parameter are only some of the possible values. Other modules include payment providers and carrier shipping methods. Use this endpoint without query parameters to see all system log entries from the store and their module values.   

      tags:
        - System Logs
      operationId: get-sites
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/SystemLog'
                  meta:
                    $ref: '#/components/schemas/IndexMeta'
      parameters:
        - schema:
            type: string
          in: path
          required: true
          name: store_hash
        - schema:
            type: integer
            default: 50
          in: query
          name: limit
          description: Results per page
        - schema:
            type: integer
            default: 1
          in: query
          name: page
          description: Numeric page of results
        - schema:
            type: string
          in: query
          name: 'date_created:min'
          description: Minimum date
        - schema:
            type: string
          in: query
          name: 'date_created:max'
          description: Maximum date
        - schema:
            type: string
            enum:
              - general messages
              - payment gateways
              - shipping quotes
              - tax quotes
              - promotion
              - notification system
              - email integration
              - ebay
              - shopping comparison
              - order settings
              - square
              - facebook
              - pinterest
              - design
              - inventory
          in: query
          name: type
          description: Filter by log type
        - schema:
            type: string
          in: query
          name: 'type:not'
          description: Exclude a type from results
        - schema:
            type: string
            enum:
              - export only
              - email message
              - theme download
              - order status
              - optimized checkout
          in: query
          name: module
          description: Filter by module
        - schema:
            type: string
          in: query
          name: 'module:not'
          description: Exclude a module from results
        - schema:
            type: integer
            enum:
              - 1
              - 2
              - 3
              - 4
          in: query
          name: severity
          description: 'Filter by severity level, as an integer. Success = 1, Notice = 2, Warning = 3, Error = 4'
        - schema:
            type: integer
          in: query
          name: 'severity:min'
          description: 'Filter by minimum severity, as an integer'
        - schema:
            type: integer
          in: query
          name: 'severity:max'
          description: 'Filter by maximum severity, as an integer'
        - schema:
            type: string
          in: query
          name: 'id:in'
          description: 'Filter by a list of log IDs, as a CSV. For example ?id:in=3,4,6'
    parameters: []
components:
  schemas:
    IndexMeta:
      type: object
      description: BC Meta payload for collection-type responses
      properties:
        pagination:
          type: object
          properties:
            total:
              type: integer
              example: 1
            count:
              type: integer
              example: 1
            per_page:
              type: integer
              example: 50
            current_page:
              type: integer
              example: 1
            total_pages:
              type: integer
              example: 1
            links:
              type: object
              properties:
                previous:
                  type: string
                  example: '?page=1&limit=50'
                current:
                  type: string
                  example: '?page=1&limit=50'
                next:
                  type: string
                  example: '?page=1&limit=50'
    ErrorResponse:
      allOf:
        - $ref: '#/components/schemas/BaseError'
        - type: object
          properties:
            errors:
              $ref: '#/components/schemas/DetailedErrors'
    BaseError:
      type: object
      description: |
        Error payload for the BigCommerce API.
      properties:
        status:
          description: |
            The HTTP status code.
          type: integer
        title:
          description: |
            The error title describing the particular error.
          type: string
        type:
          type: string
        instance:
          type: string
    DetailedErrors:
      type: object
      additionalProperties:
        type: string
    SystemLog:
      title: SystemLog
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
        module:
          type: string
        severity:
          type: string
        summary:
          type: string
        message:
          type: string
        date_created:
          type: string
          format: date-time
  parameters: {}
  requestBodies: {}
  securitySchemes:
    X-Auth-Token:
      type: apiKey
      name: X-Auth-Token
      in: header
      description: |-
        ### OAuth Scopes
        |  **UI Name** | **Permission** | **Parameter** |
        | --- | --- | --- |
        |  Store logs | read-only | store_store_logs_read_only |

        ### Headers

        |Header|Parameter|Description|
        |-|-|-|
        |`X-Auth-Token`|`access_token `|Obtained by creating an API account or installing an app in a BigCommerce control panel.|

        * For more information on Authenticating BigCommerce APIs, see: [Authentication](/api-docs/getting-started/authentication).
tags:
  - name: System Logs
security:
  - X-Auth-Token: []